export const minimalistFigmaReference = {
  fileKey: 'oaRNKV5sEnHE2gffqUbMJl',
  nodeId: '4012:4142',
  screenArtboards: ['recrutador/sobre', 'recrutador/experiencias', 'recrutador/projetos', 'recrutador/formacao'],
  capturedComponents: [
    'switch-btn',
    'i18n-toggle',
    'on-off-toggle',
    'pagination-btn',
    'card',
    'divider',
    'navigation-hint',
    'step',
    'pagination',
    'section-switch',
    'a11y-trigger',
    'links-and-actions',
  ],
  contentPagination: {
    fileKey: 'zzGQHeSIvf8Do9rPI2R8w8',
    stepNodeId: '2101:1921',
    paginationNodeId: '2101:1924',
    stepSize: 10,
    paginationGap: 6,
    paginationStepCount: 5,
    regular: {
      light: { fill: '#FFFAE5', stroke: '#000000' },
      dark: { fill: '#000000', stroke: '#FFFFFF' },
    },
    current: {
      light: { fill: '#000000', stroke: '#000000' },
      dark: { fill: '#FFFFFF', stroke: '#FFFFFF' },
    },
    hoverOpacity: 0.7,
    disabledOpacity: 0.3,
  },
  font: 'JetBrains Mono',
  fontSizes: [12, 14, 16],
  accent: '#8A38F5',
  button: {
    componentSet: 'button/collapse',
    nodeId: '2099:1949',
    states: ['default', 'hover', 'focus', 'disable'],
    appearances: ['light', 'dark'],
    fontFamily: 'JetBrains Mono',
    fontSize: 14,
    textCase: 'uppercase',
    label: 'VER MAIS',
    textColors: {
      light: {
        default: '#000000',
        hover: 'rgba(0, 0, 0, 0.7)',
        focus: 'rgba(0, 0, 0, 0.7)',
        disable: 'rgba(0, 0, 0, 0.3)',
      },
      dark: {
        default: '#FFFFFF',
        hover: 'rgba(255, 255, 255, 0.7)',
        focus: 'rgba(255, 255, 255, 0.7)',
        disable: 'rgba(255, 255, 255, 0.3)',
      },
    },
    bracketsVisibleIn: ['hover', 'focus'],
    componentSetFrame: {
      stroke: '#8A38F5',
      strokeStyle: 'dashed',
      strokeWeight: 1,
      borderRadius: 5,
      appliesToButton: false,
    },
  },
} as const;
