query Portfolio($locale: I18NLocaleCode) {
  portfolio(locale: $locale) {
    name
    last_name
    expertise_area
    seniority
    company
    location
    documentId

    highlight_text
    experience_months
    skills {
      id
      name
      technologies {
        name
      }
    }
    projects {
      id
      company
      company_url
      project_name
      desc
      start_date
      end_date
      stack {
        project_name
        technologies {
          name
          proficiency_level
        }
      }
      preview {
        alternativeText
        formats
        height
        name
        url
        width
        documentId
      }
    }
    services {
      id
      title
      description
      contact {
        url
        label
        documentId
      }
    }
    experience {
      id
      company
      company_url
      expertise_area
      start_date
      end_date
      details
      stacks {
        project_name
        technologies {
          name
          proficiency_level
        }
      }
    }
    education {
      id
      title
      institution
      description
      year
      degree_type
    }
    achievements {
      id
      badge {
        documentId
        name
        alternativeText
        width
        height
        formats
        mime
        url
      }
      title
      year
      desc
    }
    contact {
      label
      url
      documentId
    }
  }
}
