query Portfolio($locale: I18NLocaleCode) {
  portfolio(locale: $locale) {
    name
    last_name
    expertise_area
    seniority
    company
    location
    contact {
      id
      label
      url
    }
    highlight_text
    experience_months
    skills {
      id
      name
      technologies {
        name
      }
    }
    projects {
      id
      company
      company_url
      project_name
      desc
      start_date
      end_date
    }
    services {
      id
      title
      description
    }
    experience {
      id
      company
      company_url
      expertise_area
      start_date
      end_date
      details
      stack {
        id
        name
        technologies {
          name
        }
      }
    }
    education {
      id
      title
      institution
      description
      year
      degree_type
    }
    achievements {
      id
      badge {
        documentId
        name
        alternativeText
        caption
        focalPoint
        width
        height
        formats
        hash
        ext
        mime
        size
        url
      }
      title
      year
      desc
    }
  }
}
