query Projects($sort: [String], $filters: ComponentPortfolioProjectFiltersInput, $locale: I18NLocaleCode) {
  portfolio(locale: $locale) {
    projects(sort: $sort, filters: $filters) {
      id
      company
      company_url
      project_name
      desc
      start_date
      end_date
      stack {
        technologies {
          name
          proficiency_level
        }
      }
      preview {
        url
        width
        height
        formats
        alternativeText
      }
    }
  }
}
