export const curriculumData = {
  name: 'Antonio Mascarenhas',
  email: 'antonionarcilio@gmail.com',
  role: 'Frontend Developer',
  location: 'São Luís, MA — Brasil',
  phone: '(00) 0 0000-0000',
  github: 'github.com/antonionarcilio',
  githubUrl: 'https://github.com/antonionarcilio',
  linkedin: 'linkedin.com/in/antonionarcilio',
  linkedinUrl: 'https://linkedin.com/in/antonionarcilio',
  stack: 'React · Next.js · TypeScript',
  level: {
    label: 'Nível 4 — Experiência',
    fill: 72,
    sub: '1536 / 1826',
  },
  stats: [
    { value: '4+', label: 'Anos de exp de mercado' },
    { value: '12+', label: 'Tecnologias' },
    { value: '7+', label: 'Projetos' },
    { value: '∞', label: 'Vontade de aprender' },
  ],
  skills: [
    { name: 'JavaScript', pct: 80, label: '8a+', color: '#e3d34a' },
    { name: 'TypeScript', pct: 50, label: '5a+', color: '#4ea2ff' },
    { name: 'React', pct: 50, label: '5a+', color: '#2bd6ff' },
    { name: 'Next.js', pct: 40, label: '4a+', color: '#cfd5dc' },
    { name: 'WordPress', pct: 50, label: '5a+', color: '#2D789C' },
    { name: 'Node.js', pct: 20, label: '2a', color: '#4ed46a' },
    { name: 'MySQL', pct: 20, label: '2a+', color: '#4479A1' },
    { name: 'PostgreSQL', pct: 20, label: '2a+', color: '#336791' },
    { name: 'Git', pct: 80, label: '8a+', color: '#F05032' },
    { name: 'Linux', pct: 100, label: '10a+', color: '#38BFA2' },
    { name: 'Figma', pct: 20, label: '2a+', color: '#A259FF' },
    { name: 'Claude Code', pct: 4, label: '2m+', color: '#D87658' },
    { name: 'OpenCode', pct: 4, label: '2m+', color: '#5CFFE4' },
  ],
  stackPills: [
    { label: 'JavaScript', cls: 'js' },
    { label: 'TypeScript', cls: 'ts' },
    { label: 'React', cls: 'rct' },
    { label: 'Next.js', cls: 'nxt' },
    { label: 'Node.js', cls: 'nd' },
    { label: 'ClaudeCode', cls: 'wp' },
    { label: 'Figma', cls: 'html' },
    { label: 'Tailwindcss', cls: 'css' },
    { label: 'OpenCode', cls: 'git' },
    { label: 'REST APIs', cls: 'api' },
  ],
  experience: [
    {
      company: 'Escallo',
      role: 'Desenvolvedor Frontend',
      date: 'Março 2021 — Maio 2026',
      description:
        'Desenvolvimento de interfaces com React e Next.js, integrações REST, sites personalizados em WordPress, otimização de performance e SEO técnico.',
      details: [
        'Lidero a frente de frontend no time de produto, definindo padrões de componentização em React + TypeScript e migração gradual de páginas legadas para Next.js (App Router).',
        'Implementei pipelines de CI com checks de Lighthouse e bundle size, reduzindo o LCP médio em ~38% e elevando Core Web Vitals para verde em todas as páginas críticas.',
        'Mantenho temas WordPress headless com integração REST/GraphQL, além de mentoria técnica em code reviews e onboarding de novos devs.',
      ],
      stack: [
        'React',
        'Next.js',
        'JavaScript',
        'TypeScript',
        'JQuery',
        'CSS',
        'CSS Modules',
        'Tailwindcss',
        'Git',
        'GraphQL',
        'REST APIs',
        'Docker',
        'Figma',
        'CLI',
        'SSH',
        'WordPress',
        'PHP',
        'RD Station',
        'Google Analytics',
      ],
    },
  ],
  achievements: [
    { badge: '4xp', title: '4 anos de experiência', desc: '2026 — Evolução profissional contínua.' },
    { badge: 'laptop-gamer', title: 'Primeiro notebook gamer', desc: '2025 — Realização pessoal.' },
    { badge: '2xp', title: '2 anos de experiência', desc: '2024 — Desenvolvimento de sites e aplicações web.' },
    { badge: 'airplane', title: 'Primeira viagem de avião', desc: '2022 — Conhecendo Timóteo e Ipatinga.' },
    { badge: 'first-job', title: 'Primeiro emprego na área', desc: '2022 — Início da carreira em desenvolvimento.' },
    { badge: 'covid-19', title: 'Superando a COVID-19', desc: '2022 — Um novo começo após tempos difíceis.' },
    {
      badge: 'graduation',
      title: 'Conclusão da graduação',
      desc: '2021 — Diploma em Análise e Desenvolvimento de Sistemas.',
    },
    {
      badge: 'start-academic-journey',
      title: 'Início da jornada acadêmica',
      desc: '2018 — Análise e Desenvolvimento de Sistemas.',
    },
  ],
  games: [
    {
      image: '/games-badges/resident-evil-9.png',
      title: 'Resident Evil 9 — Requiem',
      sub: '45+ horas',
      tag: 'Jogo em que determinados momentos o player é o boss.',
    },
    {
      image: '/games-badges/resident-evil-4.png',
      title: 'Resident Evil 4 — Remake',
      sub: '140+ horas',
      tag: 'Daqueles jogos que você rejoga várias vezes...',
    },
    {
      image: '/games-badges/stellar-blade.png',
      title: 'Stellar Blade',
      sub: '120+ horas',
      tag: 'Excelente mecânica de combate e uma física interessante ( ͡° ͜ʖ ͡°).',
    },
    {
      image: '/games-badges/elder-ring.png',
      title: 'Elden Ring',
      sub: '250+ horas',
      tag: 'Simplesmente fora da curva, um dos melhores jogos de todos os tempos.',
    },
    {
      image: '/games-badges/automobilista-2.png',
      title: 'Automobilista 2',
      sub: '20+ horas',
      tag: 'Simulador de corrida que me surpreendeu.',
    },
    {
      image: '/games-badges/cyberpunk-2077.png',
      title: 'Cyberpunk 2077',
      sub: '60+ horas',
      tag: 'Apesar dos problemas no lançamento, é um jogo que vale a pena jogar.',
    },
    { image: '/games-badges/god-of-war-2018.png', title: 'God of War — 2018', sub: '47+ horas', tag: 'Garoto...' },
    {
      image: '/games-badges/resident-evil-3.png',
      title: 'Resident Evil 3 — Remake',
      sub: '40+ horas',
      tag: 'Um cachorro chamado Nemesis...',
    },
    {
      image: '/games-badges/resident-evil-2.png',
      title: 'Resident Evil 2 — Remake',
      sub: '80+ horas',
      tag: 'Clássico que merece ser jogado novamente.',
    },
  ],
  education: [
    {
      title: 'Análise e Desenvolvimento de Sistemas',
      institution: 'Nome da Instituição',
      description: 'Graduação',
      year: 'Concluído em 2021',
    },
  ],
};

export type CurriculumData = typeof curriculumData;
